// src/components/SocialMedia.vue
<template>
  <div>
    <h2>Social Media</h2>
    <div class="columns is-centered is-multiline">
      <div
        class="column is-one-fifth"
        v-for="edge in $static.allSocialMedia.edges"
        :key="edge.node.id"
      >
        <a target="_blank" :href="edge.node.link">
          <FA v-if="edge.node.icon" :icon="edge.node.icon" />
          {{ edge.node.site }}
        </a>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "SocialMedia"
};
</script>

<static-query>
{
	allSocialMedia {
    edges {
      node {
        id
        icon
        site
        link
      }
    }
  }
}
</static-query>

// src/lib/SocialMedia.svelte
<script>
  import socialMedia from "$content/socialmedia.json";
  import {FA} from "$lib/fa.js";

</script>



<div>
  <h2>Social Media</h2>
  <div class="columns is-centered is-multiline">
    {#each socialMedia as site}
    <div
      class="column is-one-fifth"
    >
      <a target="_blank" href={site.link}>
        <FA
          icon={site.icon}
          class="icon is-small"
        />
        {site.site}
      </a>
    </div>
    {/each}
  </div>
</div>
