// src/routes/projects/+page.svelte
<script>
  import PostCardList from "$lib/PostCardList.svelte";
  export let data;
</script>

<svelte:head>
  <title>Projects and Apps</title>
</svelte:head>

<div class="container has-text-centered h-feed">
  <div class="section">
    <h1 class="p-name">Projects, Utility Apps &amp; other Resources⚙️</h1>
    <p>
      This is a list of some of my current or past projects, as well as some
      useful resources that I compiled. Go check them out!
    </p>
  </div>
  {#each data.sections as section}
    <div class="section content">
      <h2>{section.section}</h2>
      <PostCardList posts={section.values} />
    </div>
  {/each}
</div>

// src/pages/Projects.vue
<template>
  <Layout>
    <div class="container has-text-centered">
      <div class="section content">
        <h1>Projects &amp; Demos⚙️</h1>
        <p>
          This is a list of some of my current or past projects. Go check them
          out!
        </p>
      </div>
      <div class="section content" v-if="projects.length">
        <h2>Projects</h2>
        <ProjectEntries :data="projects" />
      </div>
      <div class="section content" v-if="demos.length">
        <h2>Demos</h2>
        <ProjectEntries :data="demos" />
      </div>
    </div>
  </Layout>
</template>

<script>
import ProjectEntries from "../components/ProjectEntries";
export default {
  name: "ProjectsPage",
  components: {
    ProjectEntries
  },
  metaInfo: {
    title: "Projects & Demos"
  },
  computed: {
    projects() {
      return this.$page.projects?.edges ?? [];
    },
    demos() {
      return this.$page.demos?.edges ?? [];
    }
  }
};
</script>
<page-query>
  {
    projects: allProject {
      edges {
        node {
          id
          name
          links {
            url
            name
          }
          text
          tags
        }
      }
    }
  }
</page-query>
