// src/lib/header/Header.svelte
<script>
  let mobileMenuOpen = false;

  function tapBurger() {
    mobileMenuOpen = !mobileMenuOpen;
  }

  function closeBurger() {
    mobileMenuOpen = false;
  }
</script>

<nav
  class="navbar has-shadow is-spaced"
  role="navigation"
  aria-label="main navigation"
>
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item has-text-weight-bold" href="/">Tim Bachmann</a>
      <!-- svelte-ignore a11y-missing-attribute -->
      <a
        role="button"
        aria-label="Menu"
        on:click={tapBurger}
        class="navbar-burger burger"
      >
        <span aria-hidden="true" />
        <span aria-hidden="true" />
        <span aria-hidden="true" />
      </a>
    </div>
    <div class="navbar-menu" class:is-active={mobileMenuOpen}>
      <div class="navbar-start">
        <a on:click={closeBurger} href="/" class="navbar-item">Home</a>
        <a on:click={closeBurger} href="/projects" class="navbar-item"
          >Projects</a
        >
        <a on:click={closeBurger} href="/blog" class="navbar-item">Blog</a>
        <a class="navbar-item" target="_blank" href="https://twitter.com/TiimB"
          >Contact</a
        >
      </div>
    </div>
  </div>
</nav>

// src/components/Header.vue
<template>
  <nav class="navbar has-shadow is-spaced" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="/">Tim Bachmann</a>
        <a role="button" aria-label="Menu" @click="tapBurger" class="navbar-burger burger">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div :class="{'navbar-menu': true, 'is-active': mobileMenuOpen}">
        <div class="navbar-start">
          <router-link @click.native="closeBurger" to="/" class="navbar-item">Home</router-link>
          <router-link @click.native="closeBurger" to="/projects" class="navbar-item">Projects</router-link>
          <a class="navbar-item" target="_blank" href="https://dev.to/tiim">Blog</a>
          <a class="navbar-item" target="_blank" href="https://twitter.com/TiimB">Contact</a>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Header',
  data() {
    return {
      mobileMenuOpen: false,
    };
  },
  methods: {
    tapBurger() {
      this.mobileMenuOpen = !this.mobileMenuOpen;
    },
    closeBurger() {
      this.mobileMenuOpen = false;
    },
  },
};
</script>
